// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sandbox.proto

package grpc;

public interface ChildOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Child)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string tariff = 2;</code>
   * @return The tariff.
   */
  java.lang.String getTariff();
  /**
   * <code>string tariff = 2;</code>
   * @return The bytes for tariff.
   */
  com.google.protobuf.ByteString
      getTariffBytes();

  /**
   * <code>string gender = 3;</code>
   * @return The gender.
   */
  java.lang.String getGender();
  /**
   * <code>string gender = 3;</code>
   * @return The bytes for gender.
   */
  com.google.protobuf.ByteString
      getGenderBytes();

  /**
   * <code>string birthday = 4;</code>
   * @return The birthday.
   */
  java.lang.String getBirthday();
  /**
   * <code>string birthday = 4;</code>
   * @return The bytes for birthday.
   */
  com.google.protobuf.ByteString
      getBirthdayBytes();

  /**
   * <code>int32 parentId = 5;</code>
   * @return The parentId.
   */
  int getParentId();
}
