// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sandbox.proto

package grpc;

public interface ListChildOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ListChild)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .Child child = 1;</code>
   */
  java.util.List<grpc.Child> 
      getChildList();
  /**
   * <code>repeated .Child child = 1;</code>
   */
  grpc.Child getChild(int index);
  /**
   * <code>repeated .Child child = 1;</code>
   */
  int getChildCount();
  /**
   * <code>repeated .Child child = 1;</code>
   */
  java.util.List<? extends grpc.ChildOrBuilder> 
      getChildOrBuilderList();
  /**
   * <code>repeated .Child child = 1;</code>
   */
  grpc.ChildOrBuilder getChildOrBuilder(
      int index);
}
