// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sandbox.proto

package grpc;

/**
 * Protobuf type {@code ListChild}
 */
public final class ListChild extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ListChild)
    ListChildOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ListChild.newBuilder() to construct.
  private ListChild(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ListChild() {
    child_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ListChild();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ListChild(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              child_ = new java.util.ArrayList<grpc.Child>();
              mutable_bitField0_ |= 0x00000001;
            }
            child_.add(
                input.readMessage(grpc.Child.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        child_ = java.util.Collections.unmodifiableList(child_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return grpc.Sandbox.internal_static_ListChild_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return grpc.Sandbox.internal_static_ListChild_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            grpc.ListChild.class, grpc.ListChild.Builder.class);
  }

  public static final int CHILD_FIELD_NUMBER = 1;
  private java.util.List<grpc.Child> child_;
  /**
   * <code>repeated .Child child = 1;</code>
   */
  @java.lang.Override
  public java.util.List<grpc.Child> getChildList() {
    return child_;
  }
  /**
   * <code>repeated .Child child = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends grpc.ChildOrBuilder> 
      getChildOrBuilderList() {
    return child_;
  }
  /**
   * <code>repeated .Child child = 1;</code>
   */
  @java.lang.Override
  public int getChildCount() {
    return child_.size();
  }
  /**
   * <code>repeated .Child child = 1;</code>
   */
  @java.lang.Override
  public grpc.Child getChild(int index) {
    return child_.get(index);
  }
  /**
   * <code>repeated .Child child = 1;</code>
   */
  @java.lang.Override
  public grpc.ChildOrBuilder getChildOrBuilder(
      int index) {
    return child_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < child_.size(); i++) {
      output.writeMessage(1, child_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < child_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, child_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof grpc.ListChild)) {
      return super.equals(obj);
    }
    grpc.ListChild other = (grpc.ListChild) obj;

    if (!getChildList()
        .equals(other.getChildList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getChildCount() > 0) {
      hash = (37 * hash) + CHILD_FIELD_NUMBER;
      hash = (53 * hash) + getChildList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static grpc.ListChild parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.ListChild parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.ListChild parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.ListChild parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.ListChild parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.ListChild parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.ListChild parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.ListChild parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.ListChild parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static grpc.ListChild parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.ListChild parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.ListChild parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(grpc.ListChild prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ListChild}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ListChild)
      grpc.ListChildOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.Sandbox.internal_static_ListChild_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.Sandbox.internal_static_ListChild_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.ListChild.class, grpc.ListChild.Builder.class);
    }

    // Construct using grpc.ListChild.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getChildFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (childBuilder_ == null) {
        child_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        childBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return grpc.Sandbox.internal_static_ListChild_descriptor;
    }

    @java.lang.Override
    public grpc.ListChild getDefaultInstanceForType() {
      return grpc.ListChild.getDefaultInstance();
    }

    @java.lang.Override
    public grpc.ListChild build() {
      grpc.ListChild result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public grpc.ListChild buildPartial() {
      grpc.ListChild result = new grpc.ListChild(this);
      int from_bitField0_ = bitField0_;
      if (childBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          child_ = java.util.Collections.unmodifiableList(child_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.child_ = child_;
      } else {
        result.child_ = childBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof grpc.ListChild) {
        return mergeFrom((grpc.ListChild)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(grpc.ListChild other) {
      if (other == grpc.ListChild.getDefaultInstance()) return this;
      if (childBuilder_ == null) {
        if (!other.child_.isEmpty()) {
          if (child_.isEmpty()) {
            child_ = other.child_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureChildIsMutable();
            child_.addAll(other.child_);
          }
          onChanged();
        }
      } else {
        if (!other.child_.isEmpty()) {
          if (childBuilder_.isEmpty()) {
            childBuilder_.dispose();
            childBuilder_ = null;
            child_ = other.child_;
            bitField0_ = (bitField0_ & ~0x00000001);
            childBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getChildFieldBuilder() : null;
          } else {
            childBuilder_.addAllMessages(other.child_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      grpc.ListChild parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (grpc.ListChild) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<grpc.Child> child_ =
      java.util.Collections.emptyList();
    private void ensureChildIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        child_ = new java.util.ArrayList<grpc.Child>(child_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        grpc.Child, grpc.Child.Builder, grpc.ChildOrBuilder> childBuilder_;

    /**
     * <code>repeated .Child child = 1;</code>
     */
    public java.util.List<grpc.Child> getChildList() {
      if (childBuilder_ == null) {
        return java.util.Collections.unmodifiableList(child_);
      } else {
        return childBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .Child child = 1;</code>
     */
    public int getChildCount() {
      if (childBuilder_ == null) {
        return child_.size();
      } else {
        return childBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .Child child = 1;</code>
     */
    public grpc.Child getChild(int index) {
      if (childBuilder_ == null) {
        return child_.get(index);
      } else {
        return childBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .Child child = 1;</code>
     */
    public Builder setChild(
        int index, grpc.Child value) {
      if (childBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureChildIsMutable();
        child_.set(index, value);
        onChanged();
      } else {
        childBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Child child = 1;</code>
     */
    public Builder setChild(
        int index, grpc.Child.Builder builderForValue) {
      if (childBuilder_ == null) {
        ensureChildIsMutable();
        child_.set(index, builderForValue.build());
        onChanged();
      } else {
        childBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Child child = 1;</code>
     */
    public Builder addChild(grpc.Child value) {
      if (childBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureChildIsMutable();
        child_.add(value);
        onChanged();
      } else {
        childBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .Child child = 1;</code>
     */
    public Builder addChild(
        int index, grpc.Child value) {
      if (childBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureChildIsMutable();
        child_.add(index, value);
        onChanged();
      } else {
        childBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Child child = 1;</code>
     */
    public Builder addChild(
        grpc.Child.Builder builderForValue) {
      if (childBuilder_ == null) {
        ensureChildIsMutable();
        child_.add(builderForValue.build());
        onChanged();
      } else {
        childBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Child child = 1;</code>
     */
    public Builder addChild(
        int index, grpc.Child.Builder builderForValue) {
      if (childBuilder_ == null) {
        ensureChildIsMutable();
        child_.add(index, builderForValue.build());
        onChanged();
      } else {
        childBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Child child = 1;</code>
     */
    public Builder addAllChild(
        java.lang.Iterable<? extends grpc.Child> values) {
      if (childBuilder_ == null) {
        ensureChildIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, child_);
        onChanged();
      } else {
        childBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .Child child = 1;</code>
     */
    public Builder clearChild() {
      if (childBuilder_ == null) {
        child_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        childBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .Child child = 1;</code>
     */
    public Builder removeChild(int index) {
      if (childBuilder_ == null) {
        ensureChildIsMutable();
        child_.remove(index);
        onChanged();
      } else {
        childBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .Child child = 1;</code>
     */
    public grpc.Child.Builder getChildBuilder(
        int index) {
      return getChildFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .Child child = 1;</code>
     */
    public grpc.ChildOrBuilder getChildOrBuilder(
        int index) {
      if (childBuilder_ == null) {
        return child_.get(index);  } else {
        return childBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .Child child = 1;</code>
     */
    public java.util.List<? extends grpc.ChildOrBuilder> 
         getChildOrBuilderList() {
      if (childBuilder_ != null) {
        return childBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(child_);
      }
    }
    /**
     * <code>repeated .Child child = 1;</code>
     */
    public grpc.Child.Builder addChildBuilder() {
      return getChildFieldBuilder().addBuilder(
          grpc.Child.getDefaultInstance());
    }
    /**
     * <code>repeated .Child child = 1;</code>
     */
    public grpc.Child.Builder addChildBuilder(
        int index) {
      return getChildFieldBuilder().addBuilder(
          index, grpc.Child.getDefaultInstance());
    }
    /**
     * <code>repeated .Child child = 1;</code>
     */
    public java.util.List<grpc.Child.Builder> 
         getChildBuilderList() {
      return getChildFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        grpc.Child, grpc.Child.Builder, grpc.ChildOrBuilder> 
        getChildFieldBuilder() {
      if (childBuilder_ == null) {
        childBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            grpc.Child, grpc.Child.Builder, grpc.ChildOrBuilder>(
                child_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        child_ = null;
      }
      return childBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ListChild)
  }

  // @@protoc_insertion_point(class_scope:ListChild)
  private static final grpc.ListChild DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new grpc.ListChild();
  }

  public static grpc.ListChild getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ListChild>
      PARSER = new com.google.protobuf.AbstractParser<ListChild>() {
    @java.lang.Override
    public ListChild parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ListChild(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ListChild> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ListChild> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public grpc.ListChild getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

