// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sandbox.proto

package grpc;

public final class Sandbox {
  private Sandbox() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Parent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Parent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ParentResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ParentResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ParentId_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ParentId_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Email_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Email_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Child_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Child_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_APIResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_APIResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ParentSuccess_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ParentSuccess_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ListChild_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ListChild_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rsandbox.proto\"I\n\006Parent\022\r\n\005email\030\001 \001(\t" +
      "\022\020\n\010timeZone\030\002 \001(\t\022\014\n\004name\030\003 \001(\t\022\020\n\010pass" +
      "word\030\004 \001(\t\"?\n\016ParentResponse\022\r\n\005email\030\001 " +
      "\001(\t\022\020\n\010timeZone\030\002 \001(\t\022\014\n\004name\030\003 \001(\t\"\026\n\010P" +
      "arentId\022\n\n\002id\030\001 \001(\005\"\026\n\005Email\022\r\n\005email\030\001 " +
      "\001(\t\"Y\n\005Child\022\014\n\004name\030\001 \001(\t\022\016\n\006tariff\030\002 \001" +
      "(\t\022\016\n\006gender\030\003 \001(\t\022\020\n\010birthday\030\004 \001(\t\022\020\n\010" +
      "parentId\030\005 \001(\005\"\031\n\013APIResponse\022\n\n\002id\030\001 \001(" +
      "\005\"\037\n\rParentSuccess\022\016\n\006result\030\001 \001(\t\"\"\n\tLi" +
      "stChild\022\025\n\005child\030\001 \003(\0132\006.Child2Y\n\rParent" +
      "Service\022\032\n\004save\022\007.Parent\032\t.ParentId\022,\n\021f" +
      "indParentByEmail\022\006.Email\032\017.ParentRespons" +
      "e2U\n\014ChildService\022\026\n\004save\022\006.Child\032\006.Chil" +
      "d\022-\n\024getAllChildsByParent\022\t.ParentId\032\n.L" +
      "istChildB\010\n\004grpcP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Parent_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Parent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Parent_descriptor,
        new java.lang.String[] { "Email", "TimeZone", "Name", "Password", });
    internal_static_ParentResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ParentResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ParentResponse_descriptor,
        new java.lang.String[] { "Email", "TimeZone", "Name", });
    internal_static_ParentId_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ParentId_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ParentId_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_Email_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_Email_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Email_descriptor,
        new java.lang.String[] { "Email", });
    internal_static_Child_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_Child_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Child_descriptor,
        new java.lang.String[] { "Name", "Tariff", "Gender", "Birthday", "ParentId", });
    internal_static_APIResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_APIResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_APIResponse_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_ParentSuccess_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_ParentSuccess_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ParentSuccess_descriptor,
        new java.lang.String[] { "Result", });
    internal_static_ListChild_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_ListChild_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ListChild_descriptor,
        new java.lang.String[] { "Child", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
